### ISSUE TITLE
[video-taslak] Yazilimcı olarak calismak icin diploma sart mi?

### ISSUE THREAD

**Issue by SelmanKahya** [SelmanKahya/youtuber#7]
Merhaba,

Önümüzdeki günlerde ‘Yazilim muh olarak calismak icin diploma sart mi?’ başlığıyla bir video paylaşmayı planlıyorum.

Bu videonun içeriğini aşağıdaki şekilde organize etmeyi planlıyorum. Videoyu bu metni kullanarak çekeceğim, yorum yapabilirsiniz 😘

**Toplam video süresi:** ~5 dakika

**Amaç:** Hangi şartlarda yazılım mühendisi olabilirsiniz, yazılımcı olmak için bir diplomaya gerek var mı sorularını net bir şekilde aktarmak.

**Metin:** 
Merhaba arkadaşlar, bu videoda dünyanın herhangi bir yerinde yazilimcı olarak çalışabilmek icin bilgisayar mühendisliği, yazılım mühendisliği veya bilgisayar bilimi diplomasi şart mi?.... baska bolumden mezun olup ya da hic universite okumadan is bulmak mümkün mü -- konularını konuşacağız, dilerseniz hemen videoya geçelim.

Aslinda diploma şartmı sorusunun cevabini bulmak -oldukca- basit; mevcut is ilanlarina bakip fikir edinebiliriz. 

ben sizler icin 50 si türkiyede de 50 si yurtdisinda olmak uzere 100 ilana bakıp gereksinimleri inceledim. 

Türkiyedeki baktığım ilanların neredeyse tamamı diplomayı şart koşuyor. Yüzde 50'si spesifik olarak bilgisayar mühendisliğini, yazılım mühendislğini istiyor, yüzde 40'ın üzerinde de 'ya da benzeri bir bölümden mezun' ibaresi var. yani bilgisayar ya da yazılım bolumden mezun olmasaniz dahi onlara yakin bir muhendislik bolumunden mezun olmaniz yeterli, örneğin matematik mühendisliği, elektrik elektronik mühendisliği gibi bölümler. Yüzde 5'inde ise diploma şartından bahsedilmemiş. Bu rakamlara bakarak Türkiyede güzel bir firmada yazılımcı olarak çalışabilmek için 4 senelik diploma şart diyebiliriz.

Yurtdışında ise durum biraz daha farklı. Şuanda Amerika'da silikon vadisinde yaşıyorum. Bu civarda verilen ilanların yalnızca yüzde 10'u bilgisayar mühendisliği, yazılım mühendisliği diplomalarını şart koşuyor. kalan ilanların neredeyse tamamında ek olarak benzeri bölüm ibaresi var veya okul süresine eş profesyonel iş deneyimi bekleniyor. Yani 4 sene bilgisayar okumus olabilirsiniz, ya da cok farkli bir lisans okumus olabilirsiniz, hatta universite okumayip 4 senelik iş tecrübesi edinmis olabilirsiniz. Bunlarin hepsi kabul goruyor. Yurtdışı için baktığım hemen hemen her ilan, diploması olmayan fakat yazılım tecrübesi edinmiş bir kişinin kolaylıkla başvurabileceği tarzda. Basvurabilecegi tarzda diyorum, bu noktaya dikkatinizi cekmek istiyorum. Basvurmak ve ise kabul almak cok farkli seyler. Bir role basvuranlarin cogunlugu yuksek ortalamayla masterdan mezun olmus ve 2-3 staj tecrubesi edinmisse universite okumayip uc-dort sene tecrube edinmis kisinin kabul alma sansi neredeyse yok. Zaten universite okumadan universite süresine eş profesyonel tecrübe edinmek gerçekten zor, bu konuya az sonra değineceğim.

Türkiye ve yurtdışındaki firmaların diploma konusunda farklı davranmalarının sebebini bilmiyorum, fakat önümüzdeki senelerde bunun değişiceğini, türkiyedeki firmaların daha esnek bir yol izleyeceğini düşünüyorum. Cok farkli bolumlerden mezun olup yazilim gelistiricisi olarak calisan birey sayisi git gide artacak.

Şimdi uc farkli noktaya daha deginip ben diploma konusunda ne dusunuyorum aktarmaya calisacagim.

Bunlardan birincisi: 
Ben bu ilanlara bakarken sıradan bir yazılımcı olarak çok basit bir işe girmeyi değilde gerçekten çalışmak isteyeceğimiz, güzel bir kariyer adımı olacak işlere baktım. Yani vasatın altında bir firmada çok iş yapmayan boş bir yazılımcı olarak, az bir maaşla çalışmak gayet mümkün. fakat bu videoyu izleyen sizlerin  daha yüksek hedefleri olduğuna inanıyorum.

İkinci nokta: uzaktan ya da freelancer olarak çalışmak. bu tür pozisyonlarda gereksinimler biraz daha esnek. çünkü bu tarz işler genelde proje bazlı olduğu için pratik tecrübenin önemi daha yüksek. hatta bulundugunuz yerden yurtdışında iş bulup dolar/euro bazında iyi para kazanmak gayet mumkun.

Bir diger konu ise sertifika programlari ve online diploamalar. Artık ünivesiteler internet uzerinden yani online diploma da veriyor, hatta bazısında diploma üzerinde online alındığı dahi yazmıyor. Bu konuda ben şöyle düşünüyorum; fiziksel olarak gitme zorunluluğunuz yoksa üniversitenin sonunu getirmek, güzel bir ortalamayla mezun olmak çok zor olabiliyor, dikkat etmek lazım, ben tavsiye etmiyorum. Ek olarak yazılım üzerine oldukça fazla sertifika programı var. Bunlar ayrı bir videonun konusu olsun, fakat kısaca ben sertifika programlamarını lisans eğitimine kıyasla çok avantajlı bulmuyorum, başarı oranları düşük. Eğer güvenlik, ağ yönetimi gibi spesifik bir alanda çalışmak istiyorsanız sertifika almak sizi avantajlı konuma geçirebilir, bu konulara ilginiz varsa detaylıca araştırabilirsiniz.

Şimdi bu noktaya kadar istatistiksel verilerden bahsettik, eğer benim şahsi fikrimi sorarsanız: universite diplomasi hizlı ve başarılı bir kariyer için şart. Eger mumkunse kesinlikle iki degil dort senelik bir bolum okumakta fayda var. Bu formal egitim bir cok alanda kendinizi gelistirmenize olanak sagliyor; hem teknik alanda bilgi sahibi oluyorsunuz, hem bir muhendis olarak guzel bir sekilde yetişiyorsunuz, hem de sosyal becerilerinizi geliştirebiliyorsunuz. Lisans eğitimin üzerine bir de master yani yüksek lisans yapmak sizi işe başvuran diğer adaylardan önde tutacaktır, fakat bu bir çok başlangıç pozsiyonu için bir gereksinim değil. Ben San Francisco'da master yaptim, ve ardindan Yahoo sirketinde 
calismaya basladim. Mulakat yaptigim takimda neredeyse herkes master mezunuydu. Ortalamam 3.45 diye, 3.5'un altinda diye oldukca zorladilar. Neden ortalamamin daha yuksek olmadigini onlara birkac kez anlatmak zorunda kaldim. Az once degindigim bir nokta vardi, basvurmak ve kabul almak farkli seyler. basvuranlarin geneli bilgisayar bolumlerinden lisans diplomasi hatta yuksek lisans diplomasi almis ve ortalamasini yuksek tutmussa aslinda is ilaninda yazan sey onemini kismen kaybediyor. Ben bu sebepten oturu isinizi sansa birakmamanizi, yuksek ortalamayla universite bitirmenizi tavsiye ediyorum. Boylelikle guzel firmalarda is bulma ihtimalinizi yukselteceksiniz.

Ozetle, rakamlarlara bakılırsa bilgisayar mühendisliği, yazılım mühendisliği, bilgisayar bilimi, ya da yakın mühendislik bölümlerini bitirdiyseniz iş bulmak kolay. Eğer çok alakasız bir bölümden mezun olduysanız ya da ünversite diplomanız yoksa firmalar sizi işe almak için okul süresine eş yazılım tecrübesi istiyor olacak. Zaten sorun da burada başlıyor. İş verenlerin hepsi diplomanız olmadığı için tecrübe şartı koşuyor, sizde bir iş bulamadığınız için o tecrübeyi edinemiyorsunuz. Çıkmaz bir döngüye giriyorsunuz. Bu şartlar altında motivasyonu korumak zor, kendi başınıza bir plan çıkarıp hareket etmek neredeyse imkansız, ama tüm bu problemlerin çözümü de mevcut. yazılım ile hiç alakasız biri hangi adımları izleyerek yazılımcı olabilir, bu knouda önümüzdeki haftalarda bir video paylaşmak istiyorum, takipte kalın. O videoyu paylaşana kadar diger videolara, özellikle röportaj videolarıma bakip baska alandan yazilima gecis mumkun mu ve ne kadar zor oluyor, fikir edinebilirsiniz. 

Kısacası, ilanlara ve rakamlarlara bakılırsa yazılım ile alakali bolum okuyanların işi kolay. Guzel bir sekilde mezun olup, kendinizi muhendis olarak iyi bir sekilde yetistireceksiniz. isiniz hazir. Başka bir bölümden mezun olacaksaniz yazılımcı olarak iş bulmak hala gayet mümkün, yazilim okuyanlardan daha cok calismaniz gerekiyor. Elinizde olmayan sebeplerden oturu universite okuyamadiniz ve yazilimci olarak calismak istiyorsaniz size cok buyuk bir is dusuyor. Eger universite okuyanlardan daha yuksek bir azimle, pes etmeden, bikmadan calisirsaniz is bulabilirsiniz, ben buna inaniyorum.

Eveet, Iş bulma ihtimalini yukseltmek ve daha hizli yukselebileceginiz bir kariyer icin sartlari zorlayip iyi bir universitede yazılım bölümü okumakta fayda var --- tekrar soyluyorum EĞER şartlar müsade etmiyorsa farklı yollarla sonuca ulaşmakta mümkün, umidinizi yuksek tutun, basarabilirsiniz. Basariya giden yol bir degil, herkes icinde bulundugu sartlara gore elinden geleni yapip potansiyelini aciga cikarmakla vazifeli.

Bu kisa videonunda sonuna geldik, eger videoyu faydali bulduysaniz ne yapmaniz gerektigini biliyorsunuz, bir sonraki video gorusmek uzere hoscakalin.

**Comment by mustaphaturhan** [comment]
> Aslinda diploma şartmı sorusunun cevabini bulmak oldukca basit; mevcut is ilanlarina bakip fikir edinebiliriz. Ben sizler icin 50 si türkiyede de 50 si yurtdisinda olmak uzere 100 ilana bakıp gereksinimleri inceledim.

Aslında diploma şart mı sorusunun cevabını bulmak oldukça basit; mevcut iş ilanlarına bakıp fikir edinebiliriz. Tabii ben sizler için 50si türkiye'de, 50si yurt dışında olmak üzere 100 ilana bakıp gereksinimleri inceledim.

> Türkiyedeki baktığım ilanların yüzde 95'inde bilgisayar...

Yaptığım incelemelere göre Türkiye'deki ilanların yüzde 95'inde bilgisayar mühendisliği ya da ona benzeyen bir bölümden mezun olmanız bekleniyor. Yüzde 5'inde ise diploma şartından bahsedilmiyor.

**Comment by ThracianTR** [comment]
Merhaba arkadaşlar, bu videoda dünyanın herhangi bir yerinde yazilimcı olarak çalışabilmek icin bilgisayar mühendisliği, yazılım mühendisliği veya bilgisayar bilimiyle alakalı alanlardan diplomasi şart mi?.... yada lise düzeyinden mezun veya üniversitelerşn. farklı alanlarından mezun kişilerin kod yazmayla yeteneğiyle is bulması mümkün mü? 
bu videoda bu konuyu konuşacagız, dilerseniz hemen videoya geçelim.

Aslinda diploma şartmı sorusunun cevabini bulmak oldukca basit; mevcut is ilanlarina bakip fikir edinebiliriz.

ben sizler icin 50 si türkiyede de 50 si yurtdisinda olmak uzere 100 ilana bakıp gereksinimleri inceledim.
Türkiyedeki baktığım ilanların yüzde 95'inde bilgisayar mühendisliği yada benzeri bir bölümden mezun olmaniz bekleniyor. Yüzde 5'inde ise diploma şartından bahsedilmemiş. Diploma şartından bahseden ilanların yarısında benzeri bölümlerden ibaresi var, yani bilgisayar ya da yazılım bolumden mezun olmasaniz dahi onlara yakin bir muhendislik bolumunden mezun olmaniz yeterli.

Yurtdışında ise durum biraz daha farklı. Şuanda Amerika'da silikon vadisinde yaşıyorum. Bu civarda verilen ilanların yüzde 10'u yazılım ile alakalı bir diplomayı şart koşuyor. kalan ilanların neredeyse tamamında mühendislik benzeri bölüm ibaresi var veya okul süresine eş profesyonel iş deneyimi bekleniyor. yani neredeyse baktığım her ilan, diploması olmayan fakat yazılım tecrübesi edinmiş bir kişinin kolaylıkla başvurabileceği tarzdaydı.

**Comment by ghost** [comment]
Merhaba arkadaşlar, bu videoda dünyanın herhangi bir yerinde yazilimcı olarak çalışabilmek icin bilgisayar, yazılım mühendisliği veya bilgisayar bilimi diplomasi şart mi?.... ya da bunlar olmadan da iş bulmak mümkün mü konularını konuşacağız, dilerseniz hemen videoya geçelim.

**Comment by ghost** [comment]
> Türkiyedeki baktığım ilanların yüzde 95'inde bilgisayar müğhendisliği yada benzeri bir bölümden mezun olmaniz bekleniyor. Yüzde 5'inde ise diploma şartından bahsedilmemiş. Diploma şartından bahseden ilanların yarısında benzeri ibaresi var, yani bilgisayar ya da yazılım bolumden mezun olmasaniz dahi onlara yakin bir muhendislik bolumunden mezun olmaniz yeterli.

> 

Türkiyedeki ilanlara baktığımda yüzde 95'inde bilgisayar müğhendisliği ya da benzeri bir bölümden mezun olmaniz bekleniyor. Yüzde 5'inde ise diploma şartından bahsedilmiyor. Diploma şartından bahseden ilanların da yarısında benzeri ibaresi var, yani bilgisayar ya da yazılım bolumden mezun olmasaniz dahi onlara yakin bir muhendislik bolumunden mezun olmaniz yeterli.

**Comment by SelmanKahya** [comment]
https://www.youtube.com/watch?v=e6xtUldvuUo
